### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Starz0r/AreWeAntiCheatYet#478]
I cannot load the website lol

**Comment by Curve** [comment]
Can you please post the whole error?

**Comment by Starz0r** [comment]
Could we also get some more details, like browser, operating system, etc?

**Comment by Etaash-mathamsetty** [comment]
```
framework-5f4595e5518b5600.js:1 TypeError: Cannot read properties of undefined (reading 'length')
    at U (index-f099b90b9700010b.js:1:8539)
    at oo (framework-5f4595e5518b5600.js:1:59412)
    at Ku (framework-5f4595e5518b5600.js:1:111712)
    at Li (framework-5f4595e5518b5600.js:1:98953)
    at Ni (framework-5f4595e5518b5600.js:1:98881)
    at Pi (framework-5f4595e5518b5600.js:1:98744)
    at bi (framework-5f4595e5518b5600.js:1:95710)
    at framework-5f4595e5518b5600.js:1:45204
    at t.unstable_runWithPriority (framework-5f4595e5518b5600.js:1:129336)
    at Ql (framework-5f4595e5518b5600.js:1:44981)
```
google chrome 102 on arch linux

**Comment by Curve** [comment]
> Might be the change detection system.

Most probably, I'll push a fix in a minute

**Comment by Curve** [comment]
Build may take a minute but should work once it's done, let me know if it doesn't work in 15 minutes :D

**Comment by Etaash-mathamsetty** [comment]
yes
